### ISSUE TITLE
Release checklist for 3.14.0.0

### ISSUE THREAD

**Issue by Kleidukos** [haskell/cabal#10241]
This is the checklist of the 3.14.0.0 release, whose main highlight is [Building profiled, dynamically-linked cabal projects #9900](https://github.com/haskell/cabal/pull/9900).

If an item is actionable, please create a sub-list of the PRs that relate to it.
It is not actionable, please write “not applicable” in parentheses on the same line.

## GHC concerns

Between the 9.12 and 9.14 releases, have there been the following things that we should know about?

* [ ] New GHC flags
* [ ] New extensions
* [ ] New libraries that must be prevented from being reinstalled

## Cabal concerns

- [ ] Additions to the cabal format v3.14 have been included in the documentation with a release year
- [ ] [Preflight Checks](https://github.com/haskell/cabal/wiki/Making-a-release#c1-preflight-checks)
- [ ] [Update the SPDX license data](https://github.com/haskell/cabal/wiki/Updating-the-license-list)
- [ ] [Generate the changelogs](https://github.com/haskell/cabal/wiki/Making-a-release#c2-changelogs)
- [ ] [Bump version numbers of the libraries](https://github.com/haskell/cabal/wiki/Making-a-release#c3-bumping-version-numbers) in the release branch
- [ ] Bump the versions again, this time on **master**, to the next odd version (3.13 -> 3.15)
- [ ] [Upload the libraries on Hackage](https://github.com/haskell/cabal/wiki/Making-a-release#c4-uploading-cabal-cabal-syntax-cabal-install-and-cabal-install-solver-on-hackage)
- [ ] Publish artifacts: See [Publishing the artifacts](#c5-publishing-the-artifacts)
- [ ] Publish everything else: See [Publishing everything else](#c6-publishing-everything-else)
- [ ] Tweak things as needed, look for new issues labelled "regression in ...", merge patches that fix regressions
- [ ] Re-upload the candidates on Hackage based on the latest tag, and publish them

**Comment by Kleidukos** [comment]
@ulysses4ever May I ask you to run the [Pre-flight checks](https://github.com/haskell/cabal/wiki/Making-a-release#c1-preflight-checks) and report your findings?

**Comment by ulysses4ever** [comment]
I'm happy to. My turnaround time these days is not great though. I'll try to shoot for evening today but worst case it's Monday...

**Comment by ulysses4ever** [comment]
Actually, https://github.com/haskell/cabal/pull/10244

**Comment by ulysses4ever** [comment]
I updated the description with the list of regressions that probably may need to be fixed before the release. There are two so far...

**Comment by ulysses4ever** [comment]
A third regression, sadly: https://github.com/haskell/cabal/issues/10046

**Comment by mpickering** [comment]
Would it be possible to get a date when this release is going to be ready?

**Comment by Mikolaj** [comment]
Some more regressions I've found. Are they fixed/invalid/duplicate?

https://github.com/haskell/cabal/issues/10290

https://github.com/haskell/cabal/issues/10235

https://github.com/haskell/cabal/issues/9777

**Comment by mpickering** [comment]
@Mikolaj Not all regressions can be fixed for every release, it doesn't seem like there has been progress on #9777 nor #10290 so they could be bumped to the next release.

**Comment by Mikolaj** [comment]
> @Mikolaj Not all regressions can be fixed for every release, it doesn't seem like there has been progress on #9777 nor #10290 so they could be bumped to the next release.

Makes sense, especially if this is an interim release, between GHCs, with stress on Cabal the library not the tool. Still, this needs to be an informed decision.

**Comment by Kleidukos** [comment]
After today's meeting with @Mikolaj and @ulysses4ever, we have decided to reasonably aim for September 17th. @mpickering does this suit the GHC release agenda?

**Comment by ulysses4ever** [comment]
By the way, the timeline that works for the GHC team was discussed in https://github.com/haskell/cabal/issues/10193

**Comment by ulysses4ever** [comment]
And same for releasing the library only versus with the tool.

**Comment by ulysses4ever** [comment]
And same for releasing the library only versus with the tool.

**Comment by Kleidukos** [comment]
For compatibility purposes, we need to integrate https://github.com/haskell/cabal/pull/10411 in our release of Cabal-syntax. 

This will warrant a patch release of Cabal-syntax to go alone with the cabal-install release, but does not need to happen until mid-October.

@wz1000 will come back to us after some more testing has been done on the GHC side to confirm we can proceed with the patch release.

GHC 9.12 is expected to be released mid-November, I would like cabal-install to be readily available on ghcup by this date.

**Comment by mpickering** [comment]
#10416 is an important fix for the 3.14 release.

**Comment by wz1000** [comment]
#10419 is also something we need fixed in the 3.14 series.
