### ISSUE TITLE
Continuous integration on Windows

### ISSUE THREAD

**Issue by grayjay** [haskell/cabal#3112]
I experimented with building cabal on [AppVeyor] (https://www.appveyor.com/) by enabling it on a branch in my repository.  I wrote a simple script that can run both packages' tests.  Here's my proposed plan for setting up Windows CI:

- Wait until the cabal 1.24 release so that we can use the newer version of cabal to install dependencies.  Then `cabal update` will be able to download the index using curl.  cabal-install-1.22.0.0 failed: https://ci.appveyor.com/project/grayjay/cabal/build/1.0.6#L10764
- Address the issues relating to cabal-install test failures on Windows: #2872, #3059
- Handle the Cabal tests that fail due to missing shared libraries with GHC >= 7.8 (https://ghc.haskell.org/trac/ghc/ticket/8228).  I disabled those tests individually by using CPP on my branch.  I think it would be better to separate out the tests that use shared libraries in order to highlight what tests are being skipped.  Maybe they could go in a separate test suite, or at least a separate top-level test tree.
- Test with GHC 7.10.3 or 8.0 first, and possibly add more versions later.

Branch: https://github.com/grayjay/cabal/tree/appveyor-ghc-7.10.3
Log: https://ci.appveyor.com/project/grayjay/cabal/branch/appveyor

I also tried some other versions of GHC and the Haskell Platform but didn't have much luck.

A related issue: https://github.com/elm-lang/elm-platform/issues/105.

Remaining Windows CI issues:

- [ ] #3123 - `cabal exec` integration tests
- [ ] #3126 - file monitor unit tests

**Comment by 23Skidoo** [comment]
Thanks for looking into this! The `cabal update` failure looks weird, maybe AppVeyor is doing something  funny with the network (like forcing an HTTPS connection). We may also want to patch the HP installer script to better support silent installation - this [shouldn't be very hard](http://stackoverflow.com/questions/14445395/nsis-installer-silent-mode), and the new release will be out soon (simultaneously with GHC 8.0).

**Comment by grayjay** [comment]
@23Skidoo No problem.  I'll plan to make a pull request once cabal-install-1.24 is available.  I was able to install HP 2014.2.0.0 from Chocolatey, but then I had trouble installing cabal-install's dependencies.

**Comment by grayjay** [comment]
Does it make sense to start using AppVeyor before the release, even if the build script isn't ideal?  I was able to build cabal and run both sets of unit tests with HP 2014.2.0.0.  The problem is that I had to use `--force-reinstalls` to install cabal-install's dependencies, which led to a build plan with [multiple versions of several packages] (https://ci.appveyor.com/project/grayjay/cabal/build/1.0.28).  If it would help with testing, I can make a PR now, and then switch to a newer GHC after the release.

**Comment by 23Skidoo** [comment]
If AppVeyor won't flood us with notifications about broken builds, then sure, we can enable it now.

**Comment by grayjay** [comment]
Remaining test suite issues:
- [ ] #3059 - `sandbox delete-source` integration tests
- [ ] #3123 - `cabal exec` integration tests
- [ ] #3126 - file monitor unit tests

**Comment by BardurArantsson** [comment]
Would it be possible to somehow leverage AppVeyor's caching mechanism to shorten the build times? Perhaps it would make sense to try caching ~/.cabal/packages where the package downloads go? At least it wouldn't have to download the Internet for every single build.

**Comment by grayjay** [comment]
I reran the build that used HP 2014.2.0.0 and `--force-reinstalls` to see if I could reproduce the problem with inconsistent dependencies (https://github.com/haskell/cabal/issues/3112#issuecomment-181607936).  It seems to have been fixed in `cabal-install-1.24.0.0`. With `cabal-install-1.18.0.5`, the solver chose to reinstall `regex-base-0.93.2` and build it against `mtl-2.2.1`.  Later, when cabal configured `regex-tdfa`, it chose the instance of `regex-base-0.93.2` from the Haskell Platform, which depends on `mtl-2.1.3.1`, instead of the newly installed instance of `regex-base`.  Cabal used `mtl-2.2.1` for `regex-tdfa`'s direct dependency on `mtl`, as specified in the install plan, causing `regex-tdfa` to depend on two versions of `mtl`.

`cabal-install-1.18.0.5`: https://ci.appveyor.com/project/grayjay/cabal/build/1.0.166
`cabal-install-1.24.0.0`: https://ci.appveyor.com/project/grayjay/cabal/build/1.0.167

**Comment by ezyang** [comment]
Re dynamic library support, at least the Cabal library package test suite has a predicate testing for this, so CPP should not be needed. Don't know if you were referring to Cabal or cabal-install here.

If we need better bootstrapping, I think it would be reasonable to put a binary of Cabal up somewhere to be downloaded and then used for Appveyor.

**Comment by grayjay** [comment]
@ezyang The issue with bootstrapping has been fixed, now that the AppVeyor script can download cabal-install-1.24.  I only reran the build that used the Haskell Platform because I wanted to make sure that the bug that caused `cabal install` to use inconsistent dependencies had been fixed.

The issue with dynamic library tests in the Cabal package test suite has also been fixed (with the predicates that you mentioned).  AFAIK, the only remaining tasks are fixing the cabal-install tests that fail on Windows, and possibly using caching to shorten the build.

**Comment by ezyang** [comment]
This is live now.

**Comment by grayjay** [comment]
I left it open because appveyor.yml still skips two sets of tests.  The tests have separate issues, so I'll just add comments there.

**Comment by ezyang** [comment]
Oops, I missed that. Yeah, let's just track those separately.
