### ISSUE TITLE
Tracking ticket for Galois `new-build` requirements

### ISSUE THREAD

**Issue by acfoltzer** [haskell/cabal#3577]
I've been gathering assessments and feedback about the `new-build` features from my colleagues here at Galois. This ticket tracks the issues that we've found are particularly relevant for us, and that would need to be resolved before we can adopt `new-build` for most of our projects.

This is not meant to be exhaustive, or meant to imply that other issues are not important; this is just a scratchpad that'll evolve as I gather more feedback.

### Must resolve
These are the features that currently prevent us from adopting `new-build` on one or more projects:
- [ ] #3417: Dependency executables aren't in PATH
- [ ] #3473: Replacement needed for `cabal copy`
- [ ]  #3535: How do I haddock with new-build?

### Nice to resolve
Not showstoppers, but necessary to make it worth switching from an existing system:
- [ ] #2189: Support non-Hackage dependencies
- [ ] #3332: new-install interface for installing executables
- [ ] #3333: Garbage collecting the store
- [ ] #3391: Add flag to build all packages in project with new-build
- [ ] #3394: new-build silent failure on zip-archive-0.3.0.2

**Comment by ezyang** [comment]
@acfoltzer I posted work arounds for  #3473 and  #3535 and a work plan for  #3417.

**Comment by dcoutts** [comment]
@acfoltzer this is very useful to help prioritise, thanks for taking the time to try it out.

**Comment by hvr** [comment]
@acfoltzer Just wondering, do you really not miss/need `new-test`/`new-bench`/`new-run`?  :-)

**Comment by acfoltzer** [comment]
@dcoutts: glad it's helpful, it is for us as well!

@hvr: ha, what an omission! Is there an issue for those yet? Some of the feedback in my inbox this morning has some ideas about particular interfaces for these, so I'd like to get that written up.

**Comment by hvr** [comment]
@acfoltzer I couldn't find one, please create one or more issues to dump your ideas there! :-)

**Comment by dcoutts** [comment]
Note to self: write up ticket on locking in the store to allow concurrent installs without corrupting the store.

**Comment by dcoutts** [comment]
@aisamanra btw if you're hacking on things, you're very welcome to join #hackage and chat with us.

**Comment by dagit** [comment]
Looks like we also need: #4120
