### ISSUE TITLE
ezyang work docket

### ISSUE THREAD

**Issue by ezyang** [haskell/cabal#3588]
Things that definitely need to be done:
- [ ] Work out Haddock story

Backpack critpath:
- [X] ComponentEnabledSpec #3542
- [x] Test suite runners should take CLBI. Branch: `cabal-staging`
  - [x] Refactor into Types modules #3590
  - [x] Refactor LocalBuildInfo to make sense #3589
  - [ ] PUNTED: Move when test/bench get expanded to configure time #3599
- [x] Fix build targets to use unit IDs
- [x] Rebase Backpack
- [x] Get per-package instantiate working
- [x] Get cabal-install to instantiate Backpack packages
- [x] `--cabal-file` #3553 
- [ ] Internal libraries don't work in dependency solver (see my comment which I never implemented in IndexConversion) (But maybe it's OK?)
- [ ] Merge Backpack. Branch: `backpack` #3672
- [ ] `backpack-includes: p (* as *.ByteString)` support

GHC stuff
- [x] Stop repeatedly reading interfaces; do NO performance harm w/o Backpack
- [x] Update Cabal to HEAD https://phabricator.haskell.org/D2442
  - [x] Haddock on Cabal performance regression (NOT problem, just added extra modules so Haddock will take more memory, of course.)
- [ ] Unwind the knot-tying patchset
  - [x] Performance regression T10370 (not actually perf regression)
  - [X] Test framework regression
  - [x] Knot tying regression T8184
- [ ] Backpack proper
- Just for fun:
  - [ ] Recursive type synonym handling

Per-component build
- [x] Per-component configure. Branch: `cabal-shake` #1575
- [x] cabal install bits
- [x] new-build registering local libraries for executable only
- [ ] fix sdist bug so we can actually benefit from building only one component  #3401

Things I've agreed to do
- [ ] Preprocessor redesign #3545
- [x] BC libraries -> library/subLibraries #3580. Branch: `convenience-bc`
  - [x] Check that internal library doesn't have same name as package name
  - [ ] Test that LibV09 test suite named same as package name does the right thing
  - [x] Check that `libName` is not `Nothing` for `subLibraries`.
  - [x] Undo HookedBuildInfo change
- [ ] Put command line flag parsing back into Travis script
- [x] Haddock fixes from #3533 

Backpack on base. (Why? base is pegged to a GHC version, so there's no worry about people needing to support multiple versions of a package at the same time.)
- [ ] Teach cabal-install how to build a new copy of base
- [ ] Maybe https://ghc.haskell.org/trac/ghc/ticket/10266 ?
- [ ] Teach build system how to build Backpack packages

**Comment by phadej** [comment]
@ezyang are you planning on this issues?

**Comment by ezyang** [comment]
I think it would be best to assume these are not getting done :>
