### ISSUE TITLE
Cabal & cabal-install 3.12.1.0 release list

### ISSUE THREAD

**Issue by Mikolaj** [haskell/cabal#9204]
The machine never stops. 

3.12.1.0 is a new major release pushing out (almost) all that's on master currently.

See: [cabal 3.12 board](https://github.com/haskell/cabal/projects/17?query=is%3Aopen+sort%3Aupdated-desc)

Backports waiting to be applied (to this and/or other release branches): https://github.com/haskell/cabal/pulls?q=is%3Aopen+is%3Apr+label%3Abackport

Here are the bullet points for releasing 3.12.1.0 for Cabal & cabal-install. (This is stub for now. Please fill in.)

## Tasks
  * [ ] Changelogs

## Cabal

- [ ] Version bump (see https://github.com/haskell/cabal/pull/9033 for an old release example)
- [ ] TODO: more

## Cabal-syntax
- [ ] Version bump (see https://github.com/haskell/cabal/pull/9033 for an old release example)
- [ ] Update of SPDX license Ids & exceptions (see https://github.com/haskell/cabal/pull/9028 for an old release example)

## cabal-install

- [ ] Version bump (see https://github.com/haskell/cabal/pull/9033 for an old release example)
- [ ] TODO: more

## cabal-install-solver

- [ ] Version bump (see https://github.com/haskell/cabal/pull/9033 for an old release example)
- [ ] TODO: more

Here is the previous ticket from this series: https://github.com/haskell/cabal/issues/9008
